version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mlflow-server
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
      - MLFLOW_ARTIFACT_ROOT=/mlruns
    volumes:
      - .:/usr/src/app
      - mlruns:/mlruns
    networks:
      - ml-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ml-network

  mlflow-server:
    build: .
    command: mlflow server 
      --backend-store-uri postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB} 
      --default-artifact-root /mlruns 
      --host 0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - mlruns:/mlruns
    networks:
      - ml-network

volumes:
  postgres_data:
  mlruns:

networks:
  ml-network:
    driver: bridge